name: Build Godot Web

on:
  push:
    branches:
      - main

jobs:
  export-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Godot
        uses: firebelley/godot-export@v5.2
        with:
          godot-version: 3.5.3
          export-template: true
          export-preset: "HTML5"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/web

  deploy:
    needs: export-web
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
